//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creep
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Behaviour { get; set; }
        public int Experience { get; set; }
        public int Hp { get; set; }
        public int Str { get; set; }
        public int Dex { get; set; }
        public int Con { get; set; }
        public int Int { get; set; }
        public int Wit { get; set; }
        public int Men { get; set; }
        public double Pattack { get; set; }
        public double Mattack { get; set; }
        public double Pdef { get; set; }
        public double Mdef { get; set; }
        public double BonusAccuracy { get; set; }
        public int AttackSpeed { get; set; }
        public int Range { get; set; }
    }
}
