//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropTableItem
    {
        public int Id { get; set; }
        public int DropTableId { get; set; }
        public int ItemId { get; set; }
        public double Chance { get; set; }
    
        public virtual DropTable DropTable { get; set; }
    }
}
