//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSouls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleSouls.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    ____  _                                                     _                                  
        ///  / ___|| |__    ___    ___   ___   ___     _ __    ___ __  __| |_     _ __  ___    ___   _ __ ___  
        /// | |    | &apos;_ \  / _ \  / _ \ / __| / _ \   | &apos;_ \  / _ \\ \/ /| __|   | &apos;__|/ _ \  / _ \ | &apos;_ ` _ \ 
        /// | |___ | | | || (_) || (_) |\__ \|  __/   | | | ||  __/ &gt;  &lt; | |_    | |  | (_) || (_) || | | | | |
        ///  \____||_| |_| \___/  \___/ |___/ \___|   |_| |_| \___|/_/\_\ \__|   |_|   \___/  \___/ |_| |_| |_|.
        /// </summary>
        internal static string CrossRoadTitle {
            get {
                return ResourceManager.GetString("CrossRoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          ..:::::::::..
        ///       :::::::::::::::::
        ///     .::::::/&apos;&apos;&apos;&apos;&apos;\::::::.
        ///   .:::::/&apos;&apos;   |   &apos;&apos;\:::::.
        ///  :::::/&apos; |    |    | &apos;\:::::
        /// :::::/   |    |    |   \:::::
        ///-----/    |    |    |    \-----
        ///:::::|    |    |    |    |:::::
        ///:::::|=O=O=O=&gt; |    |    |:::::
        ///:::::|    |    |    |    |:::::
        ///-----|    |    |    |    |-----
        ///:::::|    |    |    |    |:::::
        ///:::::|    |    |    | __ |:::::
        ///:::::|    |    |    |{__}|:::::
        ///-----|    |    |    |    |-----
        ///:::::|    |    |    |    |:::::
        ///:::::|=O=O= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
    }
}
